/**
 * T35 — `<RotateSecretFlow />`.
 *
 * Two-step rotation UI:
 *
 *   Stage 1 — Initiate
 *     Operator picks the source (locally generated by us OR they paste a
 *     new client secret they got from Fief). On click we call
 *     `connections.rotateSecret`. The mutation result includes the new
 *     **plaintext webhook secret** which we display ONCE for the operator
 *     to copy (it will not be available again).
 *
 *   Stage 2 — Confirm OR Cancel (wire-up follow-up)
 *     After the operator has verified Fief is now signing/issuing with the
 *     new secret, they click "Confirm rotation" which calls
 *     `connections.confirmRotation`. The use case promotes pending → current.
 *     If they realize the rotation was a mistake (wrong pasted secret, Fief
 *     never delivered with the new key, etc.) they instead click "Cancel
 *     rotation" which calls `connections.cancelRotation` — that drops the
 *     pending slots and reverts the UI to stage 1 so they can re-initiate.
 *
 * Stage transition is driven by `rotateMutation.data` being set: once the
 * initiate call returns successfully, we switch to stage 2. Cancelling clears
 * the local mutation cache so we drop back to stage 1.
 */
import { useDashboardNotification } from "@saleor/apps-shared/use-dashboard-notification";
import { Box, Button, Text } from "@saleor/macaw-ui";
import { useState } from "react";

import { trpcClient } from "@/modules/trpc/trpc-client";

import { type RedactedProviderConnection } from "../trpc-router";

export interface RotateSecretFlowProps {
  connection: RedactedProviderConnection;
  onClose: () => void;
}

export const RotateSecretFlow = ({ connection, onClose }: RotateSecretFlowProps) => {
  const { notifySuccess, notifyError } = useDashboardNotification();

  const [useOperatorSupplied, setUseOperatorSupplied] = useState<boolean>(false);
  const [operatorSecret, setOperatorSecret] = useState<string>("");

  const rotateMutation = trpcClient.connections.rotateSecret.useMutation({
    onError(err) {
      notifyError("Rotation failed", err.message);
    },
  });

  const confirmMutation = trpcClient.connections.confirmRotation.useMutation({
    onSuccess() {
      notifySuccess("Rotation confirmed");
      onClose();
    },
    onError(err) {
      notifyError("Confirmation failed", err.message);
    },
  });

  const cancelMutation = trpcClient.connections.cancelRotation.useMutation({
    onSuccess() {
      notifySuccess("Rotation cancelled");
      /*
       * Drop the cached initiate result so the gating expression below
       * (`stage2 = rotateMutation.data`) flips back to stage 1 — the
       * operator can immediately initiate a fresh rotation without having
       * to close + reopen the panel.
       */
      rotateMutation.reset();
    },
    onError(err) {
      notifyError("Cancellation failed", err.message);
    },
  });

  const onInitiate = () => {
    rotateMutation.mutate({
      id: connection.id,
      clientSecretSource: useOperatorSupplied
        ? { mode: "operator-supplied", newClientSecret: operatorSecret }
        : { mode: "locally-generated" },
    });
  };

  const onConfirm = () => {
    confirmMutation.mutate({ id: connection.id });
  };

  const onCancelRotation = () => {
    cancelMutation.mutate({ id: connection.id });
  };

  const stage2 = rotateMutation.data;

  return (
    <Box display="flex" flexDirection="column" gap={6} data-testid="rotate-secret-flow">
      <Box display="flex" flexDirection="column" gap={2}>
        <Text size={6} fontWeight="bold">
          Rotate secret for {connection.name}
        </Text>
        <Text size={2} color="default2">
          Two-step rotation. The new webhook secret is shown once after step one — copy it before
          continuing.
        </Text>
      </Box>

      {!stage2 ? (
        /* ----- Stage 1 ----- */
        <Box display="flex" flexDirection="column" gap={4} data-testid="rotate-secret-stage-1">
          <Box display="flex" alignItems="center" gap={3}>
            <Box
              as="input"
              type="checkbox"
              id="operator-supplied-toggle"
              data-testid="operator-supplied-toggle"
              checked={useOperatorSupplied}
              onChange={(e) => setUseOperatorSupplied((e.target as HTMLInputElement).checked)}
            />
            <Box as="label" htmlFor="operator-supplied-toggle">
              <Text size={2}>I will paste a value supplied by Fief</Text>
            </Box>
          </Box>

          {useOperatorSupplied ? (
            <Box display="flex" flexDirection="column" gap={1}>
              <Box as="label" htmlFor="rotate-new-client-secret" display="block">
                <Text size={2}>New client secret *</Text>
              </Box>
              <Box
                as="input"
                id="rotate-new-client-secret"
                type="password"
                value={operatorSecret}
                onChange={(e) => setOperatorSecret((e.target as HTMLInputElement).value)}
                padding={3}
                borderRadius={3}
                borderWidth={1}
                borderStyle="solid"
                borderColor="default1"
              />
            </Box>
          ) : (
            <Text size={2} color="default2">
              A new client secret will be generated locally and sent to Fief when you click Initiate
              rotation.
            </Text>
          )}

          <Box display="flex" justifyContent="space-between" gap={3}>
            <Button
              type="button"
              variant="tertiary"
              onClick={onClose}
              disabled={rotateMutation.isLoading}
            >
              Cancel
            </Button>
            <Button
              type="button"
              onClick={onInitiate}
              disabled={
                rotateMutation.isLoading ||
                (useOperatorSupplied && operatorSecret.trim().length === 0)
              }
              data-testid="initiate-rotation-button"
            >
              {rotateMutation.isLoading ? "Rotating..." : "Initiate rotation"}
            </Button>
          </Box>
        </Box>
      ) : (
        /* ----- Stage 2 ----- */
        <Box display="flex" flexDirection="column" gap={4} data-testid="rotate-secret-stage-2">
          <Text size={2}>
            Pending secrets have been written. Copy the new webhook secret below and ensure Fief is
            delivering with it before promoting.
          </Text>
          <Box
            padding={4}
            borderRadius={3}
            borderWidth={1}
            borderStyle="solid"
            borderColor="default1"
            backgroundColor="default2"
            data-testid="pending-webhook-secret"
          >
            <Text fontWeight="bold" size={2}>
              New webhook secret (one-time):
            </Text>
            <Box as="code" __wordBreak="break-all">
              <Text size={2}>{stage2.newWebhookSecretPlaintext}</Text>
            </Box>
          </Box>
          <Box display="flex" justifyContent="space-between" gap={3}>
            <Button
              type="button"
              variant="tertiary"
              onClick={onClose}
              disabled={confirmMutation.isLoading || cancelMutation.isLoading}
            >
              Close (leave pending)
            </Button>
            <Box display="flex" gap={3}>
              <Button
                type="button"
                variant="secondary"
                onClick={onCancelRotation}
                disabled={confirmMutation.isLoading || cancelMutation.isLoading}
                data-testid="cancel-rotation-button"
              >
                {cancelMutation.isLoading ? "Cancelling..." : "Cancel rotation"}
              </Button>
              <Button
                type="button"
                onClick={onConfirm}
                disabled={confirmMutation.isLoading || cancelMutation.isLoading}
                data-testid="confirm-rotation-button"
              >
                {confirmMutation.isLoading ? "Confirming..." : "Confirm rotation"}
              </Button>
            </Box>
          </Box>
        </Box>
      )}
    </Box>
  );
};
