apiVersion: apps/v1
kind: Deployment
metadata:
  name: saleor-app-smtp-test
  namespace: whitewhale
  labels:
    app: saleor-app-smtp-test
spec:
  replicas: 2
  selector:
    matchLabels:
      app: saleor-app-smtp-test
  template:
    metadata:
      labels:
        app: saleor-app-smtp-test
    spec:
      containers:
        - name: saleor-app-smtp-test
          image: registry.digitalocean.com/whitewhale/saleor-smtp
          envFrom:
            - secretRef:
                name: mattscoinage-storefront-test-secrets
          ports:
          - containerPort: 3010
          resources:
            requests:
              memory: "512Mi"
              cpu: "250m"
            limits:
              memory: "1024Mi"
              cpu: "500m"
      topologySpreadConstraints:
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: saleor-app-smtp-test
      affinity:
        podAntiAffinity:
          preferredDuringSchedulingIgnoredDuringExecution:
            - weight: 100
              podAffinityTerm:
                labelSelector:
                  matchExpressions:
                    - key: app
                      operator: In
                      values:
                        - saleor-app-smtp-test
                topologyKey: "kubernetes.io/hostname"
