# This is a basic workflow to help you get started with Actions

name: Build Saleor API

# Controls when the workflow will run
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build_saleor_smtp:
    runs-on: ubuntu-latest
    environment: DigitalOcean-PROD

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Get python path
        id: python-path
        run: |
          echo ::set-output name=path::$(python -c "import sys; print(sys.executable)")
      - name: Sync the submodules
        run: |
          git submodule update --init
      - name: Install doctl
        uses: digitalocean/action-doctl@v2
        with:
          token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}
      - name: Build saleor smtp app; Publishes Image to Container Registry
        uses: ./.github/workflows/build_saleor_smtp
        with:
          SENTRY_AUTH_TOKEN: ${{ secrets.SENTRY_AUTH_TOKEN }}
          dockerfile: ./Dockerfile
          image_path: whitewhale/saleor-smtp

